
name: Build and deploy gender API

on:
  push:
    branches:
      - 'main'

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Auth GCP gcloud
        uses: 'google-github-actions/auth@v1'
        with:
            credentials_json: ${{ secrets.CREDENTIALS_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build docker
        working-directory: day2_api
        run: docker build -t gender-api-marc .

      - name: Tag the image
        run: docker tag gender-api-marc europe-docker.pkg.dev/ensai-2025/test-marc/gender-api-marc

      - name: Authenticate to GCP registry
        run: gcloud auth configure-docker europe-docker.pkg.dev

      - name: Create the repo
        run: gcloud artifacts repositories create test-marc --repository-format docker --location europe

      - name: Push to GCP registry
        run: docker push europe-docker.pkg.dev/ensai-2025/test-marc/gender-api-marc
